name: CI

on:
  push:
    branches: [_main]
  # pull_request:
  #   branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Prepare test
        run: npx playwright install
      - name: Install test dependencies
        run: npx playwright install-deps
      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playwright report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Screenshots
          path: tests/e2e/home.spec.ts-snapshots
          retention-days: 30
